'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  categoriesSeed,
  couponSeed,
  customerSeed,
  defaultSettings,
  formatMoney,
  orderSeed,
  productSeed,
  quoteSeed,
} from './store-data';

const storageKey = (name) => `inam-tech-zone:v3:${name}`;
const requiredNavigation = ['Home', 'Products', 'Solutions', 'Services', 'Support'];
const categoryIcons = { Hardware: '⬡', 'Power Tools': '⚒', Electrical: 'ϟ', 'CCTV & Surveillance': '◉', 'Solar Energy': '☀', Networking: '⌘', 'Alarm Systems': '◌', 'Access Control': '◆', 'Fire Alarm': '△', Accessories: '＋' };
const orderStages = ['Order Placed', 'Processing', 'Packed', 'Shipped', 'Delivered'];
const productImages = (product) => [product?.image, ...(Array.isArray(product?.gallery) ? product.gallery : [])].filter((url, index, images) => Boolean(url) && images.indexOf(url) === index).slice(0, 6);
const imageFallback = '/itz-logo-transparent.png';

function googleDriveFileId(value) {
  const url = String(value || '').trim().replaceAll('&amp;', '&');
  if (!url || !/(drive|docs)\.google\.com/i.test(url)) return '';
  const pathMatch = url.match(/\/file\/d\/([\w-]{10,})/i) || url.match(/\/d\/([\w-]{10,})/i);
  if (pathMatch) return pathMatch[1];
  try { return new URL(url).searchParams.get('id') || ''; } catch { return ''; }
}

function imageSources(value) {
  const source = String(value || '').trim().replaceAll('&amp;', '&');
  const driveId = googleDriveFileId(source);
  if (driveId) return [
    `https://drive.google.com/thumbnail?id=${encodeURIComponent(driveId)}&sz=w1600`,
    `https://lh3.googleusercontent.com/d/${encodeURIComponent(driveId)}=w1600`,
    source,
    imageFallback,
  ];
  return [source || imageFallback, imageFallback].filter((item, index, list) => list.indexOf(item) === index);
}

function StoreImage({ src, alt = '', className = '', ...props }) {
  const candidates = useMemo(() => imageSources(src), [src]);
  const [candidateIndex, setCandidateIndex] = useState(0);
  useEffect(() => { setCandidateIndex(0); }, [src]);
  const fallback = candidateIndex === candidates.length - 1 && candidates[candidateIndex] === imageFallback;
  return <img {...props} src={candidates[candidateIndex]} alt={alt} referrerPolicy="no-referrer" className={`${className} store-image${fallback ? ' store-image-fallback' : ''}`.trim()} onError={() => setCandidateIndex((index) => Math.min(index + 1, candidates.length - 1))} />;
}

function BrandLockup({ settings }) {
  return <span className="brand-lockup"><span className="brand-monogram brand-logo-media"><img src="/itz-logo-transparent.png" alt="" /></span><span className="brand-wordmark">{settings.brandName}</span></span>;
}

function ThemeToggle({ mode, onToggle, className = '' }) {
  const dark = mode === 'dark';
  return <button type="button" className={`theme-toggle ${className}`} onClick={onToggle} aria-label={`Switch to ${dark ? 'light' : 'dark'} mode`} title={`Switch to ${dark ? 'light' : 'dark'} mode`}>
    <span className="theme-toggle-track" aria-hidden="true"><i>{dark ? '☀' : '☾'}</i></span>
    <b>{dark ? 'Light' : 'Dark'}</b>
  </button>;
}

function downloadDatasheet(product, settings) {
  const lines = [settings.brandName, 'TECHNICAL PRODUCT DATASHEET', '', product.name, `SKU: ${product.sku}`, `Brand / model: ${product.brand || '—'} / ${product.model || '—'}`, `Category: ${product.category}`, `Warranty: ${product.warranty || 'Contact sales'}`, `Availability: ${product.leadTime || 'Contact sales'}`, '', 'OVERVIEW', product.description, '', 'KEY SPECIFICATIONS', ...(product.details || []).map((item) => `• ${item}`), '', `Generated by ${settings.brandName}`];
  const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${product.slug || product.sku}-datasheet.txt`;
  link.click();
  URL.revokeObjectURL(link.href);
}

function useStoredState(key, fallback) {
  const [value, setValue] = useState(fallback);
  useEffect(() => {
    try {
      const saved = localStorage.getItem(storageKey(key));
      if (saved) {
        setValue(JSON.parse(saved));
      }
    } catch {}
  }, [key]);
  useEffect(() => {
    try { localStorage.setItem(storageKey(key), JSON.stringify(value)); } catch {}
  }, [key, value]);
  useEffect(() => {
    const updateFromAnotherTab = (event) => {
      if (event.key !== storageKey(key) || !event.newValue) return;
      try { setValue(JSON.parse(event.newValue)); } catch {}
    };
    window.addEventListener('storage', updateFromAnotherTab);
    return () => window.removeEventListener('storage', updateFromAnotherTab);
  }, [key]);
  return [value, setValue];
}

async function apiCall(endpoint, action, payload = {}, token = '') {
  if (!endpoint) return null;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 20000);
  try {
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain;charset=utf-8' },
      body: JSON.stringify({ action, token, ...payload }),
      cache: 'no-store',
      signal: controller.signal,
    });
    const data = await response.json().catch(() => ({ ok: false, error: `Invalid synchronization response (${response.status})` }));
    if (!response.ok) throw new Error(data.error || `Server returned ${response.status}`);
    if (!data.ok) throw new Error(data.error || 'Request failed');
    return data;
  } catch (error) {
    if (error.name === 'AbortError') throw new Error('Synchronization timed out. Check the Apps Script deployment.');
    throw error;
  } finally { clearTimeout(timeout); }
}

function StoreHeader({ settings, categories, cartCount, wishlistCount, colorMode, currentView, onThemeToggle, onCart, onSearch, onNavigate, onMenu, menuOpen, onQuote, onTrack }) {
  const configured = (settings.headerLinks || []).map((link) => String(link).trim()).filter(Boolean).map((link) => link.toLowerCase() === 'featured' ? 'Home' : link);
  const navigation = [...configured, ...requiredNavigation.filter((required) => !configured.some((link) => link.toLowerCase() === required.toLowerCase()))];
  return <>
    <div className="announcement"><span>{settings.announcement}</span><span className="announcement-note">{settings.announcementNote}</span></div>
    <header className="site-header">
      <button className="mobile-menu-button" onClick={onMenu} aria-label="Toggle menu" aria-expanded={menuOpen}>{menuOpen ? '×' : '☰'}</button>
      <button className="brand button-reset" onClick={() => onNavigate('home')} aria-label={`${settings.brandName} home`}><BrandLockup settings={settings} /></button>
      <nav className={`desktop-nav ${menuOpen ? 'open' : ''}`} aria-label="Main navigation">
        {navigation.map((link) => { const target = link.toLowerCase() === 'home' ? 'home' : link.toLowerCase(); return <button className={currentView === target ? 'active' : ''} key={link} onClick={() => onNavigate(target)}>{link}</button>; })}
        <div className="mobile-category-nav"><span>Browse categories</span>{categories.filter((category) => category.active).map((category) => <button key={category.id} onClick={() => onNavigate('shop', category.name)}><i>{categoryIcons[category.name] || '＋'}</i>{category.name}<b>→</b></button>)}</div>
      </nav>
      <div className="header-actions">
        <button className="text-action track-action" onClick={onTrack}>Track order</button>
        <button className="text-action" onClick={onSearch}>Search</button>
        {settings.quoteEnabled && <button className="quote-header" onClick={() => onQuote(null)}>Request quote</button>}
        <ThemeToggle mode={colorMode} onToggle={onThemeToggle} />
        <button className="circle-action" onClick={() => onNavigate('wishlist')} aria-label={`Wishlist with ${wishlistCount} items`}>♡<i>{wishlistCount || ''}</i></button>
        <button className="bag-action" onClick={onCart} aria-label={`Shopping cart with ${cartCount} items`}>Cart <span>{cartCount}</span></button>
      </div>
    </header>
  </>;
}

function Hero({ settings, featured, onShop, onProduct, onQuote }) {
  const heroProduct = featured || productSeed[3];
  return <section className="hero" aria-labelledby="hero-title">
    <div className="hero-copy">
      <p className="eyebrow">{settings.heroEyebrow}</p>
      <h1 id="hero-title">{settings.heroTitle}<br /><em>{settings.heroAccent}</em></h1>
      <p className="hero-description">{settings.heroDescription}</p>
      <div className="hero-actions">
        <button className="button button-dark" onClick={onShop}>Shop technical range <span>↗</span></button>
        {settings.quoteEnabled && <button className="text-link button-reset" onClick={() => onQuote(heroProduct)}>Request project quote <span>→</span></button>}
      </div>
      <div className="hero-proof"><div><strong>10+</strong><span>Specialist categories</span></div><div><strong>24/7</strong><span>Project assistance</span></div><div><strong>100%</strong><span>Secure checkout</span></div></div>
    </div>
    <div className="hero-visual">
      <div className="hero-image-container">
        <StoreImage src={settings.heroImage} alt={heroProduct.name} />
      </div>
      <div className="image-badge"><span>ITZ</span> Engineered solutions</div>
      <button className="floating-product" onClick={() => onProduct(heroProduct)}><p>{heroProduct.name}</p><span>{formatMoney(heroProduct.price, settings)} · {heroProduct.badge || 'Project grade'} →</span></button>
    </div>
  </section>;
}

function ProductCard({ product, settings, onProduct, onAdd, wished, onWish, onCompare, compared }) {
  return <article className="product-card">
    <div className="product-card-image">
      {product.badge && <span className="product-badge">{product.badge}</span>}
      <button className={`wish-button ${wished ? 'wished' : ''}`} onClick={() => onWish(product.id)} aria-label={`${wished ? 'Remove from' : 'Add to'} wishlist`}>{wished ? '♥' : '♡'}</button>
      <button className="image-button" onClick={() => onProduct(product)}><StoreImage src={product.image} alt={product.name} loading="lazy" /></button>
      <button className="quick-add" onClick={() => onAdd(product)}>Quick add <span>＋</span></button>
    </div>
    <div className="product-card-meta"><p>{product.category} · {product.color}</p><span>★ {product.rating}</span></div>
    <button className="product-title button-reset" onClick={() => onProduct(product)}>{product.name}</button>
    <div className="product-price"><strong>{formatMoney(product.price, settings)}</strong>{product.comparePrice > product.price && <del>{formatMoney(product.comparePrice, settings)}</del>}</div>
    {settings.compareEnabled && <button className={`compare-button ${compared ? 'active' : ''}`} onClick={() => onCompare(product.id)}>{compared ? '✓ Added to compare' : '＋ Compare specifications'}</button>}
  </article>;
}

function HomeView({ settings, products, categories, wishlist, compare, onProduct, onAdd, onWish, onCompare, onShop, onQuote }) {
  const active = products.filter((p) => p.status === 'active');
  return <>
    <Hero settings={settings} featured={active.find((p) => p.slug === '24-port-gigabit-poe-switch')} onShop={onShop} onProduct={onProduct} onQuote={onQuote} />
    <section className="category-strip" aria-label="Shop categories"><span>Shop by category</span>{categories.filter((c) => c.active).map((category) => <button key={category.id} onClick={() => onShop(category.name)}>{category.name}</button>)}</section>
    <section className="category-showcase"><div className="section-heading"><div><p className="eyebrow">Everything for the job</p><h2>Shop by system</h2></div><p>From a single replacement part to a complete site deployment.</p></div><div className="category-grid">{categories.filter((c) => c.active).map((category, index) => <button key={category.id} onClick={() => onShop(category.name)}><span>{categoryIcons[category.name] || '＋'}</span><small>{String(index + 1).padStart(2, '0')}</small><strong>{category.name}</strong><i>Explore range →</i></button>)}</div></section>
    <section className="product-section">
      <div className="section-heading"><div><p className="eyebrow">Professional selection</p><h2>Project-ready essentials</h2></div><button className="text-link button-reset" onClick={() => onShop()}>View all {active.length} products <span>→</span></button></div>
      <div className="product-grid home-grid">{active.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} settings={settings} onProduct={onProduct} onAdd={onAdd} onWish={onWish} onCompare={onCompare} compared={compare.includes(product.id)} wished={wishlist.includes(product.id)} />)}</div>
    </section>
    <section className="solutions-section" id="solutions"><div className="solutions-copy"><p className="eyebrow">INAM project desk</p><h2>One partner.<br /><em>Complete systems.</em></h2><p>Tell us what you are building. Our team can help scope products, check compatibility and prepare a project quote.</p><button className="button button-light" onClick={() => onQuote(null)}>Start a project brief <span>→</span></button></div><div className="solutions-grid">{[['01','CCTV design','Camera, lens, storage and PoE planning.'],['02','Solar systems','Panels, inverter and protection sizing.'],['03','Network rollout','Switching, cabling and rack architecture.'],['04','Life safety','Alarm, access and fire system packages.']].map((item) => <article key={item[0]}><span>{item[0]}</span><strong>{item[1]}</strong><p>{item[2]}</p></article>)}</div></section>
    <section className="values-row"><div><span>01</span><strong>Project-grade selection</strong><p>Clear specifications and compatible system components.</p></div><div><span>02</span><strong>Technical guidance</strong><p>Useful answers before, during and after your purchase.</p></div><div><span>03</span><strong>Nationwide fulfillment</strong><p>Secure packing, tracked dispatch and transparent updates.</p></div></section>
  </>;
}

function ShopView({ products, categories, settings, wishlist, compare, onProduct, onAdd, onWish, onCompare, initialCategory }) {
  const [category, setCategory] = useState(initialCategory || 'All');
  const [sort, setSort] = useState('featured');
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => {
    let list = products.filter((p) => p.status === 'active' && (category === 'All' || p.category === category) && `${p.name} ${p.category} ${p.description}`.toLowerCase().includes(query.toLowerCase()));
    if (sort === 'low') list = [...list].sort((a, b) => a.price - b.price);
    if (sort === 'high') list = [...list].sort((a, b) => b.price - a.price);
    if (sort === 'rating') list = [...list].sort((a, b) => b.rating - a.rating);
    return list;
  }, [products, category, sort, query]);
  return <div className="shop-page page-shell">
    <div className="shop-heading"><p className="eyebrow">Technical catalog</p><h1>Products for <em>real projects.</em></h1><p>{filtered.length} hardware, power, security and connectivity products.</p></div>
    <div className="shop-toolbar">
      <div className="filter-tabs"><button className={category === 'All' ? 'selected' : ''} onClick={() => setCategory('All')}>All</button>{categories.filter((c) => c.active).map((c) => <button className={category === c.name ? 'selected' : ''} key={c.id} onClick={() => setCategory(c.name)}>{c.name}</button>)}</div>
      <div className="shop-tools"><label className="shop-search">⌕<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products" /></label><select value={sort} onChange={(e) => setSort(e.target.value)} aria-label="Sort products"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="rating">Top rated</option></select></div>
    </div>
    {filtered.length ? <div className="product-grid catalog-grid">{filtered.map((product) => <ProductCard key={product.id} product={product} settings={settings} onProduct={onProduct} onAdd={onAdd} onWish={onWish} onCompare={onCompare} compared={compare.includes(product.id)} wished={wishlist.includes(product.id)} />)}</div> : <div className="empty-state"><span>⌕</span><h2>No products found</h2><p>Try another category or a broader search.</p></div>}
  </div>;
}

function ProductModal({ product, settings, categories, onClose, onAdd, wished, onWish, onQuote, onCompare, compared, onCategory }) {
  const [qty, setQty] = useState(1);
  const [activeImage, setActiveImage] = useState(productImages(product)[0] || '');
  const images = productImages(product);
  const activeIndex = Math.max(0, images.indexOf(activeImage || images[0]));
  const showImage = (offset) => {
    if (images.length < 2) return;
    setActiveImage(images[(activeIndex + offset + images.length) % images.length]);
  };
  useEffect(() => {
    if (!product) return undefined;
    const previousOverflow = document.body.style.overflow;
    const closeOnEscape = (event) => event.key === 'Escape' && onClose();
    document.body.style.overflow = 'hidden';
    window.addEventListener('keydown', closeOnEscape);
    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener('keydown', closeOnEscape);
    };
  }, [product, onClose]);
  if (!product) return null;
  return <div className="overlay" role="dialog" aria-modal="true" aria-label={product.name} onMouseDown={onClose}>
    <div className="product-modal" onMouseDown={(e) => e.stopPropagation()}>
      <button className="modal-close" onClick={onClose} aria-label="Close product">×</button>
      <div className="product-detail-media">
        <div className="product-detail-image">
          <StoreImage src={activeImage || images[0]} alt={`${product.name} — image ${activeIndex + 1} of ${images.length}`} />
          {product.badge && <span>{product.badge}</span>}
          {images.length > 1 && <><button type="button" className="gallery-arrow gallery-previous" onClick={() => showImage(-1)} aria-label="Previous product image">‹</button><button type="button" className="gallery-arrow gallery-next" onClick={() => showImage(1)} aria-label="Next product image">›</button><small className="gallery-counter" aria-live="polite">{activeIndex + 1} / {images.length}</small></>}
        </div>
        {images.length > 1 && <div className="product-gallery-thumbs" aria-label="Product images">{images.map((image, index) => <button type="button" className={(activeImage || images[0]) === image ? 'active' : ''} key={`${image}-${index}`} onClick={() => setActiveImage(image)} aria-label={`View product image ${index + 1}`} aria-current={(activeImage || images[0]) === image ? 'true' : undefined}><StoreImage src={image} alt="" loading="lazy" /></button>)}</div>}
      </div>
      <div className="product-detail-copy">
        <div className="product-breadcrumb"><button onClick={() => onCategory('')}>Products</button><span>/</span><button onClick={() => onCategory(product.category)}>{product.category}</button><span>/</span><b>{product.sku}</b></div>
        <p className="eyebrow">{product.category} · {product.sku}</p><h2>{product.name}</h2><p className="detail-model">{product.brand || 'INAM Select'} · {product.model || product.sku}</p>
        <div className="detail-rating"><span>★★★★★</span> {product.rating} · {product.reviews} reviews</div>
        <div className="detail-price">{formatMoney(product.price, settings)} {product.comparePrice > product.price && <del>{formatMoney(product.comparePrice, settings)}</del>}</div>
        <p className="detail-description">{product.description}</p>
        <div className="detail-choice"><span>Configuration</span><button><i style={{ background: product.color?.includes('Red') ? '#b92323' : '#263548' }} />{product.color}</button></div>
        <ul className="detail-list">{product.details.map((detail) => <li key={detail}>{detail}</li>)}</ul>
        <div className="spec-table"><span>Warranty<strong>{product.warranty || 'Contact sales'}</strong></span><span>Lead time<strong>{product.leadTime || 'Ready to dispatch'}</strong></span></div>
        <div className="detail-stock"><span className={product.stock < 10 ? 'low' : ''} />{product.stock < 10 ? `Only ${product.stock} left` : 'In stock and ready to ship'}</div>
        <div className="detail-actions"><div className="qty-stepper"><button onClick={() => setQty(Math.max(1, qty - 1))}>−</button><span>{qty}</span><button onClick={() => setQty(qty + 1)}>＋</button></div><button className="button button-dark grow" onClick={() => { onAdd(product, qty); onClose(); }}>Add to bag <span>{formatMoney(product.price * qty, settings)}</span></button><button className={`detail-wish ${wished ? 'wished' : ''}`} onClick={() => onWish(product.id)}>{wished ? '♥' : '♡'}</button></div>
        <div className="detail-secondary">{settings.quoteEnabled && <button onClick={() => onQuote(product)}>Request project pricing</button>}{settings.compareEnabled && <button onClick={() => onCompare(product.id)}>{compared ? '✓ In comparison' : '＋ Compare product'}</button>}{settings.technicalDownloadsEnabled && <button onClick={() => downloadDatasheet(product, settings)}>↓ Download datasheet</button>}</div>
        <div className="detail-services"><span>✓ Verified specifications</span><span>✓ Secure checkout</span><span>✓ Technical support</span></div>
        <div className="detail-category-nav"><span>Explore categories</span><div>{categories.filter((category) => category.active).map((category) => <button className={category.name === product.category ? 'active' : ''} key={category.id} onClick={() => onCategory(category.name)}>{categoryIcons[category.name] || '＋'} {category.name}</button>)}</div></div>
      </div>
    </div>
  </div>;
}

function QuoteModal({ open, product, categories, settings, onClose, onSubmit }) {
  const [submitting, setSubmitting] = useState(false);
  if (!open) return null;
  const submit = async (event) => {
    event.preventDefault();
    setSubmitting(true);
    await onSubmit({ ...Object.fromEntries(new FormData(event.currentTarget)), product: product?.name || '', productId: product?.id || '' });
    setSubmitting(false);
  };
  return <div className="overlay quote-overlay" role="dialog" aria-modal="true" aria-label="Request project quote" onMouseDown={onClose}><form className="quote-modal" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><button type="button" className="modal-close" onClick={onClose}>×</button><div className="quote-intro"><p className="eyebrow">INAM project desk</p><h2>Request a professional quote.</h2><p>Share the scope and our team will review product fit, quantity pricing and availability.</p><div><span>01</span> Technical review</div><div><span>02</span> Compatibility check</div><div><span>03</span> Project pricing</div></div><div className="quote-form"><div className="form-grid"><label>Name<input name="customer" required /></label><label>Company<input name="company" /></label><label>Email<input name="email" type="email" required /></label><label>Phone / WhatsApp<input name="phone" type="tel" required /></label><label>Project type<select name="projectType" defaultValue={product?.category || categories[0]?.name}>{categories.filter((item) => item.active).map((item) => <option key={item.id}>{item.name}</option>)}</select></label><label>Required quantity<input name="quantity" type="number" min="1" defaultValue="1" /></label><label className="full">Product / system<input name="productLabel" defaultValue={product?.name || ''} placeholder="Product name or complete system" /></label><label className="full">Project details<textarea name="message" rows="4" placeholder="Site type, quantities, compatibility needs, delivery city…" /></label></div><label className="checkbox-label"><input type="checkbox" required /> I agree to be contacted about this request.</label><button className="button button-dark" disabled={submitting}>{submitting ? 'Sending request…' : 'Send quote request'} <span>→</span></button><small>Response target: within one business day · {settings.supportPhone}</small></div></form></div>;
}

function ComparePanel({ ids, products, settings, onRemove, onClear, onClose, onProduct }) {
  const selected = ids.map((id) => products.find((item) => item.id === id)).filter(Boolean);
  if (!selected.length) return null;
  return <div className="overlay compare-overlay" role="dialog" aria-modal="true" aria-label="Product comparison" onMouseDown={onClose}><section className="compare-panel" onMouseDown={(event) => event.stopPropagation()}><div className="compare-head"><div><p className="eyebrow">Side-by-side</p><h2>Technical comparison</h2><p>Compare up to three products before adding them to your project.</p></div><div><button onClick={onClear}>Clear all</button><button onClick={onClose}>×</button></div></div><div className={`compare-grid count-${selected.length}`}>{selected.map((item) => <article key={item.id}><button className="compare-remove" onClick={() => onRemove(item.id)}>×</button><div className="compare-image-box"><StoreImage src={item.image} alt={item.name} loading="lazy" /></div><p>{item.category}</p><button className="compare-title" onClick={() => { onClose(); onProduct(item); }}>{item.name}</button><strong>{formatMoney(item.price, settings)}</strong><dl><div><dt>Brand / model</dt><dd>{item.brand || '—'} · {item.model || '—'}</dd></div><div><dt>Warranty</dt><dd>{item.warranty || 'Contact sales'}</dd></div><div><dt>Availability</dt><dd>{item.leadTime || 'Contact sales'}</dd></div>{(item.details || []).slice(0, 4).map((spec) => <div key={spec}><dt>Specification</dt><dd>{spec}</dd></div>)}</dl></article>)}</div></section></div>;
}

function TrackOrderModal({ open, orders, settings, onClose }) {
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const [searching, setSearching] = useState(false);
  if (!open) return null;
  const search = async (event) => {
    event.preventDefault(); setSearching(true); setError('');
    const fields = Object.fromEntries(new FormData(event.currentTarget));
    try {
      let order;
      if (settings.apiEndpoint) {
        const response = await apiCall(settings.apiEndpoint, 'trackOrder', { orderId: fields.orderId, email: fields.email });
        order = response?.order;
      } else {
        order = orders.find((item) => item.id.toLowerCase() === String(fields.orderId).trim().toLowerCase() && item.email.toLowerCase() === String(fields.email).trim().toLowerCase());
      }
      if (!order) throw new Error('Order not found. Check the order ID and email address.');
      setResult(order);
    } catch (searchError) { setResult(null); setError(searchError.message); }
    setSearching(false);
  };
  const currentIndex = result ? Math.max(0, orderStages.indexOf(result.status === 'Processing' ? 'Processing' : result.status)) : 0;
  return <div className="overlay track-order-overlay" role="dialog" aria-modal="true" onMouseDown={onClose}><section className="track-order-modal" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><div className="track-order-intro"><span className="track-logo">ITZ</span><p className="eyebrow">Shipment intelligence</p><h2>Track your order.</h2><p>Enter the same email used at checkout and your INAM TECH ZONE order number.</p><form onSubmit={search}><label>Order number<input name="orderId" required placeholder="ITZ-1083" /></label><label>Email address<input name="email" type="email" required placeholder="you@example.com" /></label><button className="button button-dark" disabled={searching}>{searching ? 'Checking…' : 'Track shipment'} <span>→</span></button>{error && <div className="track-error">{error}</div>}</form></div><div className="track-order-result">{result ? <><div className="track-result-head"><div><p className="eyebrow">Order found</p><h3>{result.id}</h3><span>Placed {result.date} · {result.items} items</span></div><b className={`status ${String(result.status).toLowerCase().replace(' ', '-')}`}>{result.status}</b></div><div className="customer-tracking-stages">{orderStages.map((stage, index) => <div className={index <= currentIndex ? 'complete' : ''} key={stage}><i>{index < currentIndex ? '✓' : index + 1}</i><span><strong>{stage}</strong><small>{index <= currentIndex ? (result.timeline?.find((entry) => entry.stage === stage)?.date?.slice(0, 10) || result.date) : 'Pending'}</small></span></div>)}</div><div className="track-facts"><span>Courier<strong>{result.courier || 'Being assigned'}</strong></span><span>Tracking ID<strong>{result.trackingNumber || 'Not assigned yet'}</strong></span><span>Estimated delivery<strong>{result.estimatedDelivery || 'To be confirmed'}</strong></span><span>Order total<strong>{formatMoney(result.total, settings)}</strong></span></div><div className="track-latest"><span>Latest update</span><strong>{result.timeline?.at(-1)?.note || `Order is ${String(result.status).toLowerCase()}.`}</strong><small>{String(result.timeline?.at(-1)?.date || result.date).replace('T', ' ').slice(0, 16)}</small></div></> : <div className="track-placeholder"><span>◎</span><h3>Live order progress</h3><p>Your confirmed, packed, shipped and delivered milestones will appear here.</p><div><i /><i /><i /><i /><i /></div></div>}</div></section></div>;
}

function CartDrawer({ open, cart, products, settings, onClose, onQty, onRemove, onCheckout }) {
  const lines = cart.map((line) => ({ ...line, product: products.find((p) => p.id === line.id) })).filter((line) => line.product);
  const subtotal = lines.reduce((sum, line) => sum + line.product.price * line.qty, 0);
  const progress = Math.min(100, (subtotal / settings.freeShippingThreshold) * 100);
  return <><div className={`drawer-scrim ${open ? 'show' : ''}`} onClick={onClose} /><aside className={`cart-drawer ${open ? 'open' : ''}`} aria-hidden={!open}>
    <div className="drawer-header"><div><p className="eyebrow">Your selection</p><h2>Shopping bag <sup>{lines.reduce((n, l) => n + l.qty, 0)}</sup></h2></div><button onClick={onClose} aria-label="Close bag">×</button></div>
    {subtotal < settings.freeShippingThreshold ? <div className="shipping-progress"><p>Add {formatMoney(settings.freeShippingThreshold - subtotal, settings)} for complimentary shipping</p><div><span style={{ width: `${progress}%` }} /></div></div> : <div className="shipping-earned">✓ You&apos;ve unlocked complimentary shipping</div>}
    <div className="cart-lines">{lines.length ? lines.map(({ product, qty }) => <div className="cart-line" key={product.id}><div className="cart-thumb"><StoreImage src={product.image} alt="" loading="lazy" /></div><div><p>{product.category}</p><h3>{product.name}</h3><span>{product.color}</span><div className="mini-stepper"><button onClick={() => onQty(product.id, qty - 1)}>−</button><span>{qty}</span><button onClick={() => onQty(product.id, qty + 1)}>＋</button></div></div><div className="line-price"><strong>{formatMoney(product.price * qty, settings)}</strong><button onClick={() => onRemove(product.id)}>Remove</button></div></div>) : <div className="empty-state"><span>🎒</span><h3>Your bag is empty</h3><p>Browse our catalog to add products.</p></div>}</div>
    {Boolean(lines.length) && <div className="drawer-footer"><div className="summary-row"><span>Subtotal</span><strong>{formatMoney(subtotal, settings)}</strong></div><p className="summary-note">Taxes and shipping calculated during checkout.</p><button className="button button-dark full" onClick={onCheckout}>Proceed to checkout <span>→</span></button></div>}
  </aside></>;
}

export default function StoreFront() {
  const [settings] = useStoredState('settings', defaultSettings);
  const [categories] = useStoredState('categories', categoriesSeed);
  const [products] = useStoredState('products', productSeed);
  const [orders] = useStoredState('orders', orderSeed);
  const [cart, setCart] = useStoredState('cart', [{ id: 'p1', qty: 1 }]);
  const [wishlist, setWishlist] = useStoredState('wishlist', ['p2', 'p4']);
  const [compare, setCompare] = useStoredState('compare', []);
  const [colorMode, setColorMode] = useStoredState('theme', 'dark');

  const [currentView, setCurrentView] = useState('home');
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [activeProduct, setActiveProduct] = useState(null);
  const [cartOpen, setCartOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [quoteProduct, setQuoteProduct] = useState(null);
  const [quoteModalOpen, setQuoteModalOpen] = useState(false);
  const [trackModalOpen, setTrackModalOpen] = useState(false);

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', colorMode);
  }, [colorMode]);

  const cartCount = useMemo(() => cart.reduce((total, line) => total + line.qty, 0), [cart]);

  const handleNavigate = (view, category = 'All') => {
    setCurrentView(view);
    setSelectedCategory(category);
    setMenuOpen(false);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleAddToCart = (product, qty = 1) => {
    setCart((prev) => {
      const existing = prev.find((item) => item.id === product.id);
      if (existing) {
        return prev.map((item) => item.id === product.id ? { ...item, qty: item.qty + qty } : item);
      }
      return [...prev, { id: product.id, qty }];
    });
    setCartOpen(true);
  };

  const handleCartQty = (id, newQty) => {
    if (newQty <= 0) {
      setCart((prev) => prev.filter((item) => item.id !== id));
    } else {
      setCart((prev) => prev.map((item) => item.id === id ? { ...item, qty: newQty } : item));
    }
  };

  const handleToggleWishlist = (id) => {
    setWishlist((prev) => prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]);
  };

  const handleToggleCompare = (id) => {
    setCompare((prev) => {
      if (prev.includes(id)) return prev.filter((item) => item !== id);
      if (prev.length >= 3) return prev;
      return [...prev, id];
    });
  };

  const handleQuoteRequest = (product) => {
    setQuoteProduct(product);
    setQuoteModalOpen(true);
  };

  return (
    <div className="app-shell">
      {/* تمام امیجز کے سائز کو درست اور رسپانسو رکھنے کا Global CSS */}
      <style html-global="true">{`
        .store-image {
          width: 100% !important;
          height: 100% !important;
          object-fit: cover !important;
          object-position: center !important;
          display: block !important;
        }

        .store-image-fallback {
          object-fit: contain !important;
          padding: 8px !important;
          background-color: rgba(255, 255, 255, 0.05) !important;
        }

        /* 1. Product Cards (Square aspect ratio for Mobile & PC) */
        .product-card-image {
          position: relative;
          width: 100%;
          aspect-ratio: 1 / 1;
          overflow: hidden;
          border-radius: 8px;
          background-color: rgba(0, 0, 0, 0.04);
        }

        .product-card-image .image-button {
          width: 100%;
          height: 100%;
          display: block;
          padding: 0;
          border: none;
          background: transparent;
        }

        /* 2. Hero Section Main Banner Image */
        .hero-visual {
          position: relative;
          width: 100%;
          aspect-ratio: 4 / 3;
          max-height: 420px;
          overflow: hidden;
          border-radius: 12px;
        }

        .hero-image-container {
          width: 100%;
          height: 100%;
        }

        /* 3. Product Popup / Detail Modal Image */
        .product-detail-image {
          position: relative;
          width: 100%;
          height: 380px;
          overflow: hidden;
          border-radius: 12px;
          background-color: rgba(0, 0, 0, 0.04);
        }

        .product-gallery-thumbs {
          display: flex;
          gap: 8px;
          margin-top: 10px;
        }

        .product-gallery-thumbs button {
          width: 60px;
          height: 60px;
          aspect-ratio: 1 / 1;
          overflow: hidden;
          border-radius: 6px;
          border: 1px solid rgba(255, 255, 255, 0.2);
          padding: 0;
          background: transparent;
        }

        /* 4. Cart Drawer Items & Compare Items */
        .cart-thumb, .compare-image-box {
          width: 64px;
          height: 64px;
          aspect-ratio: 1 / 1;
          overflow: hidden;
          border-radius: 6px;
          flex-shrink: 0;
        }

        .compare-image-box {
          width: 100%;
          height: 160px;
          margin-bottom: 12px;
        }

        /* 5. Mobile Dynamic Adjustments */
        @media (max-width: 768px) {
          .hero-visual {
            aspect-ratio: 16 / 9;
            max-height: 260px;
          }

          .product-detail-image {
            height: 250px;
          }

          .product-gallery-thumbs button {
            width: 48px;
            height: 48px;
          }
        }
      `}</style>

      <StoreHeader
        settings={settings}
        categories={categories}
        cartCount={cartCount}
        wishlistCount={wishlist.length}
        colorMode={colorMode}
        currentView={currentView}
        onThemeToggle={() => setColorMode(colorMode === 'dark' ? 'light' : 'dark')}
        onCart={() => setCartOpen(true)}
        onSearch={() => handleNavigate('shop')}
        onNavigate={handleNavigate}
        onMenu={() => setMenuOpen(!menuOpen)}
        menuOpen={menuOpen}
        onQuote={() => handleQuoteRequest(null)}
        onTrack={() => setTrackModalOpen(true)}
      />

      <main className="main-content">
        {currentView === 'home' && (
          <HomeView
            settings={settings}
            products={products}
            categories={categories}
            wishlist={wishlist}
            compare={compare}
            onProduct={setActiveProduct}
            onAdd={handleAddToCart}
            onWish={handleToggleWishlist}
            onCompare={handleToggleCompare}
            onShop={(cat) => handleNavigate('shop', cat)}
            onQuote={handleQuoteRequest}
          />
        )}
        {currentView === 'shop' && (
          <ShopView
            products={products}
            categories={categories}
            settings={settings}
            wishlist={wishlist}
            compare={compare}
            onProduct={setActiveProduct}
            onAdd={handleAddToCart}
            onWish={handleToggleWishlist}
            onCompare={handleToggleCompare}
            initialCategory={selectedCategory}
          />
        )}
      </main>

      <ProductModal
        product={activeProduct}
        settings={settings}
        categories={categories}
        onClose={() => setActiveProduct(null)}
        onAdd={handleAddToCart}
        wished={wishlist.includes(activeProduct?.id)}
        onWish={handleToggleWishlist}
        onQuote={handleQuoteRequest}
        onCompare={handleToggleCompare}
        compared={compare.includes(activeProduct?.id)}
        onCategory={(cat) => {
          setActiveProduct(null);
          handleNavigate('shop', cat);
        }}
      />

      <QuoteModal
        open={quoteModalOpen}
        product={quoteProduct}
        categories={categories}
        settings={settings}
        onClose={() => setQuoteModalOpen(false)}
        onSubmit={async (data) => {
          console.log('Quote Request Submitted:', data);
          setQuoteModalOpen(false);
        }}
      />

      <TrackOrderModal
        open={trackModalOpen}
        orders={orders}
        settings={settings}
        onClose={() => setTrackModalOpen(false)}
      />

      <ComparePanel
        ids={compare}
        products={products}
        settings={settings}
        onRemove={handleToggleCompare}
        onClear={() => setCompare([])}
        onClose={() => setCompare([])}
        onProduct={setActiveProduct}
      />

      <CartDrawer
        open={cartOpen}
        cart={cart}
        products={products}
        settings={settings}
        onClose={() => setCartOpen(false)}
        onQty={handleCartQty}
        onRemove={(id) => handleCartQty(id, 0)}
        onCheckout={() => alert('Proceeding to checkout execution...')}
      />
    </div>
  );
}
